apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: splitbot
resources:
  - ../../base
  - splitbot-sealed.yaml
images:
  - name: ghcr.io/erix/splitbot
    newTag: latest # {"$imagepolicy":"flux-system:splitbot:tag"}
