apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: splitbot
  namespace: flux-system
spec:
  interval: 10m
  path: ./k8s/overlays/local
  prune: true
  wait: true
  timeout: 3m
  sourceRef:
    kind: GitRepository
    name: splitbot
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: splitbot
      namespace: splitbot
